export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const FETCH_JOB_SEEKERS = "FETCH_JOB_SEEKERS";
export const FETCH_JOB_PROPOSAL = "FETCH_JOB_PROPOSAL";